const REPO='pangyilee/lee-pangyi-website',PATH='content.json';let data,sha;const sections=[['site','基本資料'],['about','關於'],['news','News'],['events','Calendar'],['works','影片與作品'],['projects','Projects'],['socials','社群連結']];const labels={nameZh:'中文姓名',nameEn:'英文姓名',roleZh:'中文身份',roleEn:'英文身份',quoteZh:'中文名言',quoteEn:'英文名言',heroImage:'主視覺圖片網址',email:'Email',locationZh:'中文地點',locationEn:'英文地點',eyebrowZh:'中文眉題',eyebrowEn:'英文眉題',titleZh:'中文標題',titleEn:'英文標題',bodyZh:'中文介紹',bodyEn:'英文介紹',date:'日期 YYYY-MM-DD',time:'時間',categoryZh:'中文分類',categoryEn:'英文分類',titleZh:'中文標題',titleEn:'英文標題',summaryZh:'中文摘要',summaryEn:'英文摘要',descriptionZh:'中文說明',descriptionEn:'英文說明',image:'圖片網址',url:'連結',venueZh:'中文場地',venueEn:'英文場地',cityZh:'中文城市',cityEn:'英文城市',status:'狀態 upcoming / past',type:'類型 youtube / image',year:'年份',roleZh:'中文角色',roleEn:'英文角色'};
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;');
async function load(){const r=await fetch(PATH+'?'+Date.now());data=await r.json();render();message.textContent='已載入網站內容。'}
function field(path,k,v){const long=/body|summary|description|quote/i.test(k);return `<div class="field"><label>${labels[k]||k}</label>${long?`<textarea data-path="${path}.${k}">${esc(v)}</textarea>`:`<input data-path="${path}.${k}" value="${esc(v)}">`}</div>`}
function render(){adminNav.innerHTML=sections.map(([k,n],i)=>`<button type="button" data-open="${k}">${n}</button>`).join('');editor.innerHTML=sections.map(([k,n],i)=>{const val=data[k];if(Array.isArray(val))return `<div class="panel ${i?'':'active'}" data-panel="${k}"><h2>${n}</h2><div data-list="${k}">${val.map((x,j)=>item(k,x,j)).join('')}</div><button class="add" type="button" data-add="${k}">＋ 新增項目</button></div>`;return `<div class="panel ${i?'':'active'}" data-panel="${k}"><h2>${n}</h2><div class="dual">${Object.entries(val).map(([a,b])=>field(k,a,b)).join('')}</div></div>`}).join('');bind()}
function item(sec,obj,i){return `<div class="item"><div class="item-head"><b>#${i+1}</b><button class="remove" type="button" data-remove="${sec}.${i}">刪除</button></div><div class="dual">${Object.entries(obj).map(([k,v])=>field(`${sec}.${i}`,k,v)).join('')}</div></div>`}
function sync(){document.querySelectorAll('[data-path]').forEach(el=>{const p=el.dataset.path.split('.');if(p.length===2)data[p[0]][p[1]]=el.value;else data[p[0]][+p[1]][p[2]]=el.value})}
function bind(){document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));document.querySelector(`[data-panel="${b.dataset.open}"]`).classList.add('active')});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{sync();const [s,i]=b.dataset.remove.split('.');data[s].splice(+i,1);render();document.querySelector(`[data-open="${s}"]`).click()});document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{sync();const s=b.dataset.add,template=data[s][0]?JSON.parse(JSON.stringify(data[s][0])):{};Object.keys(template).forEach(k=>template[k]='');data[s].push(template);render();document.querySelector(`[data-open="${s}"]`).click()})}
connect.onclick=()=>{sessionStorage.setItem('pyl-token',token.value);state.textContent=token.value?'已備妥':'尚未連線'};token.value=sessionStorage.getItem('pyl-token')||'';if(token.value)state.textContent='已備妥';
async function api(method,body){const t=token.value||sessionStorage.getItem('pyl-token');if(!t)throw Error('請先輸入 GitHub Token。');const r=await fetch(`https://api.github.com/repos/${REPO}/contents/${PATH}`,{method,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${t}`,'X-GitHub-Api-Version':'2022-11-28'},body:body&&JSON.stringify(body)});if(!r.ok)throw Error(`${r.status}: ${await r.text()}`);return r.json()}
save.onclick=async()=>{try{sync();message.textContent='正在同步…';const current=await api('GET');const content=btoa(unescape(encodeURIComponent(JSON.stringify(data,null,2)+'\n')));const out=await api('PUT',{message:'Update website content',content,sha:current.sha});sha=out.content.sha;message.textContent='✓ 已成功提交。GitHub Pages 通常會在 1–2 分鐘內更新。';state.textContent='同步完成'}catch(e){message.textContent='同步失敗：'+e.message}};
preview.onclick=()=>{sync();const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='content-preview.json';a.click()};document.querySelector('#load').onclick=load;load();
