document.title="李邦儀內容管理";document.head.insertAdjacentHTML("beforeend","<link rel=\"icon\" type=\"image/svg+xml\" href=\"../brand-logo.svg\"><link rel=\"apple-touch-icon\" href=\"../brand-logo.svg\">");document.querySelector("#studio > header b").innerHTML="<img class=\"admin-brand-icon\" src=\"../brand-logo.svg\" alt=\"Pang-Yi Lee Logo\"><span>CONTENT STUDIO</span>";
const REPO='pangyilee/lee-pangyi-website',PATH='content.json';let data,sha;const sections=[['site','基本資料'],['pageImages','各分頁主視覺'],['about','關於'],['news','News'],['events','Calendar'],['works','影片與作品'],['classes','CLASS 授課'],['socials','社群連結']];const labels={nameZh:'中文姓名',nameEn:'英文姓名',roleZh:'中文身份',roleEn:'英文身份',quoteZh:'中文名言',quoteEn:'英文名言',heroImage:'主視覺圖片網址',email:'Email',locationZh:'中文地點',locationEn:'英文地點',eyebrowZh:'中文眉題',eyebrowEn:'英文眉題',titleZh:'中文標題',titleEn:'英文標題',bodyZh:'中文介紹',bodyEn:'英文介紹',date:'日期 YYYY-MM-DD',time:'時間',categoryZh:'中文分類',categoryEn:'英文分類',titleZh:'中文標題',titleEn:'英文標題',summaryZh:'中文摘要',summaryEn:'英文摘要',descriptionZh:'中文說明',descriptionEn:'英文說明',image:'圖片網址',url:'連結',venueZh:'中文場地',venueEn:'英文場地',cityZh:'中文城市',cityEn:'英文城市',status:'狀態 upcoming / past',type:'類型 youtube / image',year:'年份',roleZh:'中文角色',roleEn:'英文角色'};
const pageImageLabels={home:'首頁主視覺',about:'關於頁主視覺',classes:'授課頁主視覺',contact:'Contact 頁主視覺'};
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;');
async function load(){const r=await fetch('/api/content?'+Date.now(),{cache:'no-store'});data=await r.json();delete data.projects;if(!data.classes){try{const defaults=await fetch('../content.json?'+Date.now(),{cache:'no-store'}).then(x=>x.json());data.classes=defaults.classes||{}}catch(_){data.classes={}}}const fallback=data.site.heroImage||'',saved=data.pageImages||{};data.pageImages={home:saved.home||fallback,about:saved.about||fallback,classes:saved.classes||data.classes.image||fallback,contact:saved.contact||fallback};render();message.textContent='已載入網站內容。'}
function field(path,k,v){const long=/body|summary|description|quote/i.test(k),isImage=k==='heroImage'||k==='image'||path==='pageImages',label=path==='pageImages'?pageImageLabels[k]:(labels[k]||k);return `<div class="field ${isImage?'image-field':''}"><label>${label}</label>${long?`<textarea data-path="${path}.${k}">${esc(v)}</textarea>`:`<input data-path="${path}.${k}" value="${esc(v)}">`}${isImage?`<div class="image-tools">${v?`<img src="${esc(v)}" alt="圖片預覽">`:''}<label class="upload-button">選擇並上傳圖片<input class="image-upload" type="file" accept="image/jpeg,image/png,image/webp,image/gif" data-target="${path}.${k}"></label><small>支援 JPG、PNG、WebP、GIF，建議小於 5MB。</small></div>`:''}</div>`}
function render(){adminNav.innerHTML=sections.map(([k,n])=>`<button type="button" data-open="${k}">${n}</button>`).join('')+'<button type="button" data-open="inquiries">收到的訊息</button>';editor.innerHTML=sections.map(([k,n],i)=>{const val=data[k];if(Array.isArray(val))return `<div class="panel ${i?'':'active'}" data-panel="${k}"><h2>${n}</h2><div data-list="${k}">${val.map((x,j)=>item(k,x,j)).join('')}</div><button class="add" type="button" data-add="${k}">＋ 新增項目</button></div>`;return `<div class="panel ${i?'':'active'}" data-panel="${k}"><h2>${n}</h2><div class="dual">${Object.entries(val).map(([a,b])=>field(k,a,b)).join('')}</div></div>`}).join('')+'<div class="panel" data-panel="inquiries"><h2>收到的訊息</h2><div data-inquiries><p>載入中…</p></div></div>';bind();loadInquiries()}
function item(sec,obj,i){return `<div class="item"><div class="item-head"><b>#${i+1}</b><button class="remove" type="button" data-remove="${sec}.${i}">刪除</button></div><div class="dual">${Object.entries(obj).map(([k,v])=>field(`${sec}.${i}`,k,v)).join('')}</div></div>`}
async function loadInquiries(){const target=document.querySelector('[data-inquiries]');if(!target)return;try{const r=await fetch('/api/manage-inquiries',{cache:'no-store',credentials:'same-origin'});if(!r.ok)throw Error(r.status);const {items=[]}=await r.json();target.innerHTML=items.length?items.map(x=>`<article class="inquiry-entry"><header><h3>${esc(x.name)} · <a href="mailto:${esc(x.email)}">${esc(x.email)}</a></h3><time>${esc(new Date(x.createdAt).toLocaleString('zh-TW'))}</time></header><small>${esc(x.subject||'general')}${x.phone?' · '+esc(x.phone):''}</small><p>${esc(x.message)}</p></article>`).join(''):'<p>目前還沒有收到訊息。</p>'}catch(_){target.innerHTML='<p>暫時無法載入收到的訊息。</p>'}}
function sync(){document.querySelectorAll('[data-path]').forEach(el=>{const p=el.dataset.path.split('.');if(p.length===2)data[p[0]][p[1]]=el.value;else data[p[0]][+p[1]][p[2]]=el.value})}
function bind(){document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));document.querySelector(`[data-panel="${b.dataset.open}"]`).classList.add('active')});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{sync();const [s,i]=b.dataset.remove.split('.');data[s].splice(+i,1);render();document.querySelector(`[data-open="${s}"]`).click()});document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{sync();const s=b.dataset.add,template=data[s][0]?JSON.parse(JSON.stringify(data[s][0])):{};Object.keys(template).forEach(k=>template[k]='');data[s].push(template);render();document.querySelector(`[data-open="${s}"]`).click()});document.querySelectorAll('.image-upload').forEach(input=>input.onchange=()=>uploadImage(input))}
async function uploadImage(input){const file=input.files[0];if(!file)return;if(file.size>5*1024*1024){message.textContent='圖片超過 5MB，請先壓縮後再上傳。';input.value='';return}try{message.textContent='正在上傳圖片…';const r=await fetch('/api/manage-upload',{method:'POST',credentials:'same-origin',headers:{'content-type':file.type},body:await file.arrayBuffer()});if(r.status===401)throw Error('登入已逾時，請重新登入。');if(!r.ok){let detail='';try{detail=(await r.json()).error||''}catch(_){}throw Error(detail||`上傳服務錯誤（${r.status}）`)}const out=await r.json(),field=document.querySelector(`[data-path="${input.dataset.target}"]`);field.value=out.url;sync();const tools=input.closest('.image-tools'),old=tools.querySelector('img'),url=URL.createObjectURL(file);if(old)old.src=url;else tools.insertAdjacentHTML('afterbegin',`<img src="${url}" alt="圖片預覽">`);message.textContent='✓ 圖片已上傳。請再按「儲存並同步前台」套用到網站。'}catch(e){message.textContent='圖片上傳失敗：'+(e.message==='Failed to fetch'?'目前無法連上上傳服務，請重新整理後再試。':e.message)}finally{input.value=''}}
save.onclick=async()=>{try{sync();message.textContent='正在儲存…';save.disabled=true;const r=await fetch('/api/manage-content',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json','accept':'application/json'},body:JSON.stringify(data)});if(r.status===401){studio.hidden=true;loginGate.hidden=false;throw Error('登入已逾時，請重新登入後再儲存。')}if(!r.ok){let detail='';try{detail=(await r.json()).error||''}catch(_){detail=await r.text()}throw Error(detail||`伺服器錯誤（${r.status}）`)}message.textContent='✓ 已儲存，公開網站已同步更新。'}catch(e){message.textContent='儲存失敗：'+(e.message==='Failed to fetch'?'目前無法連上儲存服務，請重新整理後再試。':e.message)}finally{save.disabled=false}};
preview.onclick=()=>{sync();const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='content-preview.json';a.click()};document.querySelector('#load').onclick=load;

async function enterStudio(){loginGate.hidden=true;studio.hidden=false;await load()}
async function checkAuth(){try{const r=await fetch('/api/auth/session',{cache:'no-store'}),result=await r.json();if(result.authenticated)await enterStudio()}catch(_){} }
loginForm.onsubmit=async(event)=>{event.preventDefault();loginMessage.textContent='登入中…';const r=await fetch('/api/auth/login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({password:adminPassword.value})});if(!r.ok){loginMessage.textContent='密碼錯誤，請再試一次。';adminPassword.select();return}adminPassword.value='';loginMessage.textContent='';await enterStudio()};
logout.onclick=async()=>{await fetch('/api/auth/logout',{method:'POST'});studio.hidden=true;loginGate.hidden=false;adminPassword.focus()};
checkAuth();
