let data,lang=localStorage.getItem('pyl-lang')||'zh';
const I18N={zh:{heroKicker:'音樂家・媒體工作者',discover:'進入網站',newsLabel:'動態與分享',newsIntro:'音樂資訊、創作札記，以及正在發生的事。',calendarLabel:'演出行程',upcoming:'近期演出',past:'過往演出',worksLabel:'影音與創作',worksTitle:'影片與作品',worksIntro:'聽見作品，也看見聲音背後的故事。',projectsLabel:'媒體經歷',contactLabel:'聯絡與合作',contactTitle:'讓我們一起<br>創造下一個聲音。',contactBody:'演出邀約、媒體合作、製作與其他有趣的提案，歡迎來信。',rights:'版權所有。',nav:['首頁','關於','News','Calendar','影片與作品','Projects','Contact'],read:'閱讀',venue:'場地'},en:{heroKicker:'Musician · Media Professional',discover:'Discover',newsLabel:'Updates & Notes',newsIntro:'Music discoveries, creative notes, and what is happening now.',calendarLabel:'Performances',upcoming:'Upcoming',past:'Archive',worksLabel:'Film & Creative Work',worksTitle:'Works',worksIntro:'Listen to the work and see the stories behind the sound.',projectsLabel:'Media Experience',contactLabel:'Contact & Collaboration',contactTitle:'Let’s create the<br>next sound together.',contactBody:'For performances, media collaborations, production, and intriguing proposals—get in touch.',rights:'All rights reserved.',nav:['Home','About','News','Calendar','Works','Projects','Contact'],read:'View',venue:'Venue'}};
const ids=['home','about','news','calendar','works','projects','contact'];
const key=(base)=>base+(lang==='zh'?'Zh':'En');
function render(){document.documentElement.lang=lang==='zh'?'zh-Hant':'en';document.querySelector('#language').textContent=lang==='zh'?'EN':'中文';document.querySelector('#nav').innerHTML=ids.map((id,i)=>`<a href="#${id}">${I18N[lang].nav[i]}</a>`).join('');document.querySelectorAll('[data-t]').forEach(el=>el.innerHTML=I18N[lang][el.dataset.t]);document.querySelectorAll('[data-site]').forEach(el=>el.textContent=data.site[key(el.dataset.site.replace(/Zh|En/,''))]||data.site[el.dataset.site]);document.querySelectorAll('[data-about]').forEach(el=>{const b=el.dataset.about.replace(/Zh|En/,'');el.textContent=data.about[key(b)]});document.querySelector('#heroImage').src=data.site.heroImage;document.querySelector('#aboutImage').src=data.site.heroImage;document.querySelector('#emailLink').textContent=data.site.email+' ↗';document.querySelector('#emailLink').href='mailto:'+data.site.email;document.querySelector('#location').textContent=data.site[key('location')];renderNews();renderEvents(document.querySelector('.tabs .active')?.dataset.events||'upcoming');renderWorks();renderProjects();renderSocials();}
function renderNews(){newsGrid.innerHTML=data.news.map((n,i)=>`<article class="card"><div class="thumb">${n.image?`<img src="${n.image}" alt="">`:`<span>0${i+1}</span>`}</div><div class="meta"><span>${n[key('category')]}</span><time>${n.date}</time></div><h3>${n[key('title')]}</h3><p>${n[key('summary')]}</p></article>`).join('')}
function renderEvents(status){eventsList.innerHTML=data.events.filter(e=>e.status===status).sort((a,b)=>status==='upcoming'?a.date.localeCompare(b.date):b.date.localeCompare(a.date)).map(e=>`<article class="event"><time>${e.date.slice(5).replace('-',' / ')}</time><div><h3>${e[key('title')]}</h3><p>${e.time}</p></div><div><b>${e[key('venue')]}</b><p>${e[key('city')]}</p></div>${e.link?`<a href="${e.link}" target="_blank">↗</a>`:'<span>—</span>'}</article>`).join('')||`<p>No events yet.</p>`}
function yt(url){const m=url.match(/(?:youtu\.be\/|v=|embed\/)([\w-]{11})/);return m?`https://img.youtube.com/vi/${m[1]}/maxresdefault.jpg`:''}
function renderWorks(){worksGrid.innerHTML=data.works.map((w,i)=>`<article class="card"><a href="${w.url||'#'}" target="_blank"><div class="thumb">${w.image||yt(w.url)?`<img src="${w.image||yt(w.url)}" alt="">`:`<span>PLAY ${i+1}</span>`}</div><div class="meta"><span>${w.type}</span><span>↗</span></div><h3>${w[key('title')]}</h3><p>${w[key('description')]}</p></a></article>`).join('')}
function renderProjects(){projectsList.innerHTML=data.projects.map(p=>`<article class="project"><span>${p.year}</span><h3>${p[key('title')]}</h3><p>${p[key('role')]}</p><p>${p[key('description')]}</p></article>`).join('')}
function renderSocials(){const labels={instagram:'IG',facebook:'FB',youtube:'YT',soundcloud:'SC'};socials.innerHTML=Object.entries(data.socials).map(([k,v])=>`<a href="${v}" target="_blank" aria-label="${k}">${labels[k]}</a>`).join('')}
fetch('content.json?'+Date.now()).then(r=>r.json()).then(d=>{data=d;render()}).catch(()=>document.body.innerHTML='<p style="padding:10vw">Unable to load content.</p>');
language.onclick=()=>{lang=lang==='zh'?'en':'zh';localStorage.setItem('pyl-lang',lang);render()};menu.onclick=()=>nav.classList.toggle('open');document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderEvents(b.dataset.events)});document.querySelector('#year').textContent=new Date().getFullYear();new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.15}).observe(document.querySelector('.hero-copy'));document.querySelectorAll('.reveal').forEach(x=>new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12}).observe(x));
